project:
  type: website

website:
  title: "Alessandro Gerada"
  navbar:
    right:
      - about.qmd
      - resources.qmd
      - icon: github
        href: https://github.com/agerada
      - icon: twitter
        href: https://twitter.com/alegerada
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



