---
title: "Post-apocalyptic microbiology"
date: 2025-06-21
bibliography: bibs/2025-06-21-post-apocalypitc-microbiology.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/refs/heads/master/vancouver.csl
---

After the recent release of 28 Years Later---a sequel to the zombie apocalypse movies 28 Days Later and 28 Weeks Later---I have been thinking... How would the microbiologists fare in such a bleak world. Would our knowledge become irrelevant? The threat of antimicrobial resistance seems inconsequential compared to the existential challenges encountered in these sorts of movies or literature.

It's intersting to think about this "what if?" scenario. Are there any microbiology-specific skills or knowledge that would be useful in such a setting?

Before we explore this, some terms and conditions must be set. Firstly, we will only consider situations where some societal structure or governance is in place. In a truly anarchistic society, where chaos reigns and physical strength is the daily currency, microbiology is effectively irrelevant. Therefore, we will only consider situations were there is some organised structure or society in place. The expectation here is that there would be some sort of organised society, with some leadership structure (not necessarily democratic). Similarly, some formal or informal rule of law that allows resources to be shared relatively equitably.

Secondly, the cause of this unfortuante apocalpyse may be infectious in origin, but not necessarily so. I am interested in the wider contributions a microbiologist could offer a post-apocalyptic society. 

It is likely that the most important role would be advising the _de facto_ governing body on the control of infectious disease through cohorting of the infected and their contacts, and other preventative measures such as basic hygeine. This could be targeted towards the infective cause of the calamity (if it is indeed caused by a communicable disease), or to the inevitable infectious ailments that would arise in a situation where modern societal structures, including healthcare, have collapsed.

Already it is hard to imagine plausible contributions beyond this. The clinical management of patients would fall under general doctor care (see [Where There Is No Doctor](https://en.wikipedia.org/wiki/Where_There_Is_No_Doctor)) --- the microbiologist offers little more in practice [@wernerWhereThereNo2009]. One may imagine whether a barebones laboratory could be constructed and run. A light microscope that uses natural could be a valuable tool in the right hands (and eyes). Old-school solid culture media could be prepared by drawing blood from a sheep or horse, onto a clean glass petri dish (or similar shape) [@buxtonBloodAgarPlates2005]. Gelatin could be prepared by boiling animal bones and added as a solidifying agent. The media could be inoculated with infected material collected from various clinical sites. Indeed, gelatin was an important substance in the early days of bacteriology. The hydrolysis of gelatin, through gelatinase, was used as a biochemical test to identify certain pathogenic bacteria, for example to differentiate _Staphylococcus aureus_ (gelatinase positive) from the coagulase-positive _Staphylococci_ [@delacruzGelatinHydrolysisTest2012].

Although rudimentary laboratory testing such as this is a curiousity, far more important is the availability of key antimicrobial agents. Rather than attempting to build a proto-laboratory, the sensible microbiologist would try to source a collection of critical antimicrobials. These drugs must be easy to store, easy to consume (i.e., oral medication), and have a broad range of activity against important bacteria. Although this resource would be a finite one [^make_abx], as long as kept secure and in reasonable storage conditions, the drugs could be used well past their nominal expiry date. Studies have shown little degradation in antimicrobials that have been in storage for over 50 years [@davidoEfficacyExpiredAntibiotics2024; @germanExtremelyLongTime2010]! 

[^make_abx]: In theory it is possible to produce more antimicrobial, for example by fermenting _Penicillium rubens_ to produce penicillin. Almost certainly not practical, and any fermentation facilities would be more useful for the production of beer.
